[build]
publish = "dist/"
command = "rustup default stable && curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash && rustup target add wasm32-unknown-unknown && cargo binstall trunk && trunk build --release"

[build.environment]
RUST_VERSION = "1.78.0"
